/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

const c = (v) => `rgb(var(--${v}) / <alpha-value>)`;

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: c('background'),
        surface: c('surface'),
        'surface-bright': c('surface-bright'),
        'surface-dim': c('surface-dim'),
        'surface-container-lowest': c('surface-container-lowest'),
        'surface-container-low': c('surface-container-low'),
        'surface-container': c('surface-container'),
        'surface-container-high': c('surface-container-high'),
        'surface-container-highest': c('surface-container-highest'),
        'surface-variant': c('surface-variant'),
        'on-surface': c('on-surface'),
        'on-surface-variant': c('on-surface-variant'),
        'inverse-surface': c('inverse-surface'),
        'inverse-on-surface': c('inverse-on-surface'),
        outline: c('outline'),
        'outline-variant': c('outline-variant'),
        primary: c('primary'),
        'on-primary': c('on-primary'),
        'primary-container': c('primary-container'),
        'on-primary-container': c('on-primary-container'),
        'primary-fixed': c('primary-fixed'),
        'on-primary-fixed': c('on-primary-fixed'),
        'inverse-primary': c('inverse-primary'),
        secondary: c('secondary'),
        'on-secondary': c('on-secondary'),
        'secondary-container': c('secondary-container'),
        'on-secondary-container': c('on-secondary-container'),
        'secondary-fixed': c('secondary-fixed'),
        'on-secondary-fixed': c('on-secondary-fixed'),
        tertiary: c('tertiary'),
        'on-tertiary': c('on-tertiary'),
        'tertiary-container': c('tertiary-container'),
        'on-tertiary-container': c('on-tertiary-container'),
        'tertiary-fixed': c('tertiary-fixed'),
        'on-tertiary-fixed': c('on-tertiary-fixed'),
        error: c('error'),
        'on-error': c('on-error'),
        'error-container': c('error-container'),
        'on-error-container': c('on-error-container'),
        'g-blue': c('g-blue'),
        'g-red': c('g-red'),
        'g-green': c('g-green'),
        'g-yellow': c('g-yellow'),
        'g-green-text': c('g-green-text'),
        'g-green-tint': c('g-green-tint'),
        scrim: c('scrim'),
      },
      borderRadius: { card: '16px', action: '24px' },
      spacing: { unit: '8px', gutter: '16px' },
      fontFamily: {
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'button-text': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [forms, containerQueries],
};
